Repository COS301-SE-2024/Smart-Inventory, pull requests merged in 2024-10, with the labels that each got.

#282 Merge/dashboard
  src/app/pages/dashboard/dashboard.component.css
  src/app/pages/dashboard/dashboard.component.html
  src/app/pages/dashboard/dashboard.component.ts
Labels: bug

#291 Updating develop
  README.md
  documents/Demo 4/ARS.pdf
  documents/Demo 4/Coding Standards.pdf
  documents/Demo 4/DeploymentDiag.png
  documents/Demo 4/DeploymentModel.jpg
  documents/Demo 4/DesignSpec.pdf
  documents/Demo 4/Predictive Analytics.pdf
  documents/Demo 4/SRS.pdf
  documents/Demo 4/Service Contract.pdf
  documents/Demo 4/Technical Installation Manual.pdf
  documents/Demo 4/Testing Manual.pdf
  documents/Demo 4/User Manual.pdf
  media/logo-no-background.png
  src/app/components/reports/activity-report/activity-report.component.ts
  src/app/components/reports/supplier-report/supplier-report.component.css
  src/app/pages/dashboard/dashboard.component.css
  src/app/pages/dashboard/dashboard.component.html
  src/app/pages/dashboard/dashboard.component.ts
  src/app/pages/inventory/inventory.component.ts
  src/app/pages/reports/reports.component.ts
  src/app/pages/suppliers/suppliers.component.ts
  src/app/pages/team/team.component.ts
Labels: develop

#293 Feat/context menu
  src/app/components/grid/context-menu/context-menu.component.css
  src/app/components/grid/context-menu/context-menu.component.html
  src/app/components/grid/context-menu/context-menu.component.spec.ts
  src/app/components/grid/context-menu/context-menu.component.ts
  src/app/components/grid/grid.component.html
  src/app/components/grid/grid.component.ts
  src/app/components/modal/addmember/addmember.component.html
  src/app/components/modal/customize/customize.component.html
  src/app/pages/inventory-summary/inventory-summary.component.css
  src/app/pages/inventory-summary/inventory-summary.component.html
  src/app/pages/inventory-summary/inventory-summary.component.ts
  src/app/pages/inventory/inventory.component.ts
  src/app/pages/suppliers/suppliers.component.css
  src/app/pages/suppliers/suppliers.component.html
  src/app/pages/suppliers/suppliers.component.ts
Labels: bug, enhancement, develop

#298 Feat/dashboard fixes
  src/app/components/add-widget-side-pane/add-widget-side-pane.component.css
  src/app/components/add-widget-side-pane/add-widget-side-pane.component.html
  src/app/components/add-widget-side-pane/add-widget-side-pane.component.ts
  src/app/pages/dashboard/dashboard.component.html
  src/app/pages/dashboard/dashboard.component.ts
Labels: develop

#299 Develop dashboard Fixes
  angular.json
  src/app/components/add-widget-side-pane/add-widget-side-pane.component.css
  src/app/components/add-widget-side-pane/add-widget-side-pane.component.html
  src/app/components/add-widget-side-pane/add-widget-side-pane.component.ts
  src/app/pages/dashboard/dashboard.component.html
  src/app/pages/dashboard/dashboard.component.ts
  src/app/pages/landing-page/help-dialog/help-dialog.component.css
  src/app/pages/landing-page/help-dialog/help-dialog.component.html
  src/app/pages/landing-page/help-dialog/help-dialog.component.spec.ts
  src/app/pages/landing-page/help-dialog/help-dialog.component.ts
  src/app/pages/landing-page/landing-page.component.css
  src/app/pages/landing-page/landing-page.component.html
  src/app/pages/landing-page/landing-page.component.ts
Labels: useability changes
